Added project roles in diploma roles and fixed reaction role
sinsniwal/iitm-server-bot pull request #29
Opened 2023-07-07 06:44 UTC by sankarannamboodiri

Added project roles in diploma roles.
The diploma+foundational was not removing diploma subject roles while unreacting. This was fixed

2023-07-07 07:14 UTC, IndraReddy5 approved these changes

2023-07-17 07:32 UTC, sinsniwal requested changes

2023-07-17 07:32 UTC, sinsniwal commented on cogs/reaction.py
> +
maybe this line is responsible for failed test case

2023-07-17 07:32 UTC, sinsniwal commented on cogs/reaction.py
> +                new_roles -= self.diploma_subject_roles
Instead of using the minus operator, we can use set discard.

2023-07-17 07:49 UTC, sinsniwal commented on cogs/reaction.py
> +                new_roles -= self.diploma_subject_roles
in this case we have to use difference_update instead of discard

2023-07-17 08:13 UTC, sankarannamboodiri commented on cogs/reaction.py
> +
The issue is still persisting.

2023-07-17 08:20 UTC, sinsniwal commented on cogs/reaction.py
> +        1022158918237048832, # BDM Project
Before #, we can have one more space, making it consistent

2023-07-17 08:29 UTC, sinsniwal approved these changes

2023-07-17 08:29 UTC, merged